"""add admin

Revision ID: 0bc878449679
Revises: b5641923bd3c
Create Date: 2018-10-27 12:23:05.965374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0bc878449679'
down_revision = 'b5641923bd3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('admin', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_user_admin'), 'user', ['admin'], unique=False)
    op.drop_index('ix_user_vorig_bezoekende_praktijk', table_name='user')
    op.create_index(op.f('ix_user_vorig_bezoekende_praktijk'), 'user', ['vorig_bezoekende_praktijk'], unique=False)
    op.drop_index('ix_user_vorig_te_bezoeken_praktijk', table_name='user')
    op.create_index(op.f('ix_user_vorig_te_bezoeken_praktijk'), 'user', ['vorig_te_bezoeken_praktijk'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_vorig_te_bezoeken_praktijk'), table_name='user')
    op.create_index('ix_user_vorig_te_bezoeken_praktijk', 'user', ['vorig_te_bezoeken_praktijk'], unique=1)
    op.drop_index(op.f('ix_user_vorig_bezoekende_praktijk'), table_name='user')
    op.create_index('ix_user_vorig_bezoekende_praktijk', 'user', ['vorig_bezoekende_praktijk'], unique=1)
    op.drop_index(op.f('ix_user_admin'), table_name='user')
    op.drop_column('user', 'admin')
    # ### end Alembic commands ###
