"""added te bezoeken en word bezocht door

Revision ID: 7d303c7e6be3
Revises: 5510e6e50953
Create Date: 2018-10-05 14:41:49.648571

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d303c7e6be3'
down_revision = '5510e6e50953'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('bezoekende_praktijk', sa.String(length=25), nullable=True))
    op.add_column('user', sa.Column('num_therapeuten', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('te_bezoeken_praktijk', sa.String(length=25), nullable=True))
    op.create_index(op.f('ix_user_bezoekende_praktijk'), 'user', ['bezoekende_praktijk'], unique=True)
    op.create_index(op.f('ix_user_te_bezoeken_praktijk'), 'user', ['te_bezoeken_praktijk'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_te_bezoeken_praktijk'), table_name='user')
    op.drop_index(op.f('ix_user_bezoekende_praktijk'), table_name='user')
    op.drop_column('user', 'te_bezoeken_praktijk')
    op.drop_column('user', 'num_therapeuten')
    op.drop_column('user', 'bezoekende_praktijk')
    # ### end Alembic commands ###
