"""add admin false

Revision ID: cd9f1a30f31a
Revises: 0bc878449679
Create Date: 2018-10-27 12:31:23.322958

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd9f1a30f31a'
down_revision = '0bc878449679'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_admin', table_name='user')
    op.drop_column('user', 'admin')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('admin', sa.BOOLEAN(), nullable=True))
    op.create_index('ix_user_admin', 'user', ['admin'], unique=False)
    # ### end Alembic commands ###
