"""added more datafield vorige and regio

Revision ID: eb69f2c0b1f8
Revises: 7d303c7e6be3
Create Date: 2018-10-18 17:15:43.184228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb69f2c0b1f8'
down_revision = '7d303c7e6be3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('regio', sa.String(length=25), nullable=True))
    op.add_column('user', sa.Column('vorig_bezoekende_praktijk', sa.String(length=25), nullable=True))
    op.add_column('user', sa.Column('vorig_catagorie', sa.String(length=25), nullable=True))
    op.add_column('user', sa.Column('vorig_color', sa.String(length=25), nullable=True))
    op.add_column('user', sa.Column('vorig_name_code', sa.String(length=25), nullable=True))
    op.add_column('user', sa.Column('vorig_te_bezoeken_praktijk', sa.String(length=25), nullable=True))
    op.create_index(op.f('ix_user_regio'), 'user', ['regio'], unique=False)
    op.create_index(op.f('ix_user_vorig_bezoekende_praktijk'), 'user', ['vorig_bezoekende_praktijk'], unique=True)
    op.create_index(op.f('ix_user_vorig_catagorie'), 'user', ['vorig_catagorie'], unique=False)
    op.create_index(op.f('ix_user_vorig_color'), 'user', ['vorig_color'], unique=False)
    op.create_index(op.f('ix_user_vorig_name_code'), 'user', ['vorig_name_code'], unique=False)
    op.create_index(op.f('ix_user_vorig_te_bezoeken_praktijk'), 'user', ['vorig_te_bezoeken_praktijk'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_vorig_te_bezoeken_praktijk'), table_name='user')
    op.drop_index(op.f('ix_user_vorig_name_code'), table_name='user')
    op.drop_index(op.f('ix_user_vorig_color'), table_name='user')
    op.drop_index(op.f('ix_user_vorig_catagorie'), table_name='user')
    op.drop_index(op.f('ix_user_vorig_bezoekende_praktijk'), table_name='user')
    op.drop_index(op.f('ix_user_regio'), table_name='user')
    op.drop_column('user', 'vorig_te_bezoeken_praktijk')
    op.drop_column('user', 'vorig_name_code')
    op.drop_column('user', 'vorig_color')
    op.drop_column('user', 'vorig_catagorie')
    op.drop_column('user', 'vorig_bezoekende_praktijk')
    op.drop_column('user', 'regio')
    # ### end Alembic commands ###
